[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "gtts>=2.5.4",
    "python-telegram-bot==20.8",
    "requests>=2.32.4",
    "telegram>=0.0.1",
]
